# Generated by Django 4.2.10 on 2024-06-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejumawura", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ejumawura.community",
            ),
        ),
    ]
