# Generated by Django 4.2.10 on 2024-06-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ejumawura", "0006_remove_post_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="community",
        ),
    ]
