# Generated by Django 4.2.10 on 2024-06-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ejumawura", "0007_remove_post_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ejumawura.community",
            ),
        ),
    ]
